services:
  - type: web
    name: fraud-api
    env: docker
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          property: connectionString
      - key: SERVICE_TYPE
        value: api

  - type: worker
    name: fraud-worker
    env: docker
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          property: connectionString
      - key: SERVICE_TYPE
        value: worker

  - type: web
    name: fraud-flower
    env: docker
    plan: free
    envVars:
      - key: REDIS_URL
        fromService:
          name: redis
          property: connectionString
      - key: SERVICE_TYPE
        value: flower

  - type: redis
    name: redis
    ipAllowList: []